### ISSUE TITLE
Capture mode not working on Yandex

### ISSUE THREAD

**Issue by colemar** [dessant/search-by-image#375]
**System**

* OS name: Windows
* OS version: 10
* Browser name: Chrome
* Browser version: 136.0.7103.93
* Extension version: 8.1.0

**Bug description**
About 7 days ago Yandex stopped working with capture mode.
The web page opens but it simply shows the main input form.
![Image](https://github.com/user-attachments/assets/21d07501-b70a-4c1b-8cf9-bbcfde15300f)
I haven't done anything like install new extensions or change browser settings.

**Logs**

```
script.js:1 Error: DOM node not found: .input_js_inited .input__cbir-button button
script.js:1 Uncaught (in promise) Error: DOM node not found: .input_js_inited .input__cbir-button button
    at script.js:1:20223
(anonymous) @ script.js:1
```

**Comment by dessant** [comment]
Yandex has updated their site, the issue was fixed in https://github.com/dessant/search-by-image/commit/c798855e07b0633f26713413c9674bb9da58e174. I'll probably release a new version today.

**Comment by Gitubhu** [comment]
Yandex image search is failing again.

**Comment by dessant** [comment]
@Gitubhu, the issue is fixed in version 8.2.1, you just haven't yet received the extension update.

**Comment by colemar** [comment]
@dessant I [downloaded](https://github.com/dessant/search-by-image/releases/download/v8.2.1/search_by_image-8.2.1-chrome.zip) 8.2.1 from here and the issue is still there.

**Comment by colemar** [comment]
> [@dessant](https://github.com/dessant) I [downloaded](https://github.com/dessant/search-by-image/releases/download/v8.2.1/search_by_image-8.2.1-chrome.zip) 8.2.1 from here and the issue is still there.

Wait, Yandex Images paste-search does not work also!
I mean, you copy some image (for example with a screen grab utility) then paste (CTRL-V) when the web page from `https://yandex.com/images/` is in focus.

**Comment by dessant** [comment]
@colemar, I'm not sure what's happening on your end, but I can no longer reproduce the issue with version 8.2.1.

**Comment by Gitubhu** [comment]
For some reason the camera icon doesn't work on the images tab, but it works on the web tab

https://github.com/user-attachments/assets/b0e542a4-5542-4100-a54f-becfeb16e983

(The mouse icon doesn´t show but you can see how the icon camera is highlighted when i click on it)

**Comment by dessant** [comment]
@Gitubhu, we wouldn't be able to help you based on the limited information you shared, though I don't think the popup not working on Yandex is related to this extension. You should do some basic testing to figure out if this is a bug in the site, or if it's caused by one of the extensions, then open a bug report by filling out the issue template if it is caused by this extension.

**Comment by Gitubhu** [comment]
i have tested it on firefox and edge, obtaining the same results in both. Is probably a bug on yandex end or they have changed how image search works, time will tell.

**Comment by dessant** [comment]
I have opened a new bug report to track the issue with the unresponsive button on Yandex: https://github.com/dessant/search-by-image/issues/383

**Comment by dessant** [comment]
@colemar, it's possible that you were seeing this bug on Yandex: https://github.com/dessant/search-by-image/issues/383

Version 8.2.2 contains a change that should sidestep the issue.
